### ISSUE TITLE
Generate Darwin from API and commit to repo.

### ISSUE THREAD

**Issue by carloslozano** [AdaptiveMe/adaptive-arp-api#141]
1. Create milestone (if it doesn't exist) for the API specification tag. #137 
2. Commit code to repo.
3. Create issue in repo for the new API changes. #136

**Comment by fnva** [comment]
Destination folder:

https://github.com/AdaptiveMe/adaptive-arp-api-lib-darwin/tree/master/Pod/Classes

**Comment by fnva** [comment]
Closed.
