### ISSUE TITLE
Swift - Singleton Pattern

### ISSUE THREAD

**Issue by fnva** [AdaptiveMe/adaptive-arp-api#160]
Seems to with Swift 1.2 we can create **static vars**, and are no longer supported the **class vars**: http://codereview.stackexchange.com/questions/80246/swift-1-2-singleton-implementation

It's necessary to change the following code in the Swift generator:

```swift
class var sharedInstance : AppRegistryBridge {
  struct Static {
    static let instance : AppRegistryBridge = AppRegistryBridge(delegate: AppRegistryDelegate())
  }
  return Static.instance
}
```
by:
```swift
public static let sharedInstance = AppRegistryBridge(delegate: AppRegistryDelegate())
```

**Comment by carloslozano** [comment]
Done. Next generation of API will include fix.
