### ISSUE TITLE
Swift. Auto-generate enhancements

### ISSUE THREAD

**Issue by fnva** [AdaptiveMe/adaptive-arp-api#88]
- **Implement JSON constructor in Swift Beans** @see https://gist.github.com/fnva/4a13cff38b1f3d5a7d43
- **Generate AppRegistry**. Instantiate and Registry all Services
- **"Generate Service Method Handler"**. Evaluate the possibility to auto-generate this service...
- **Generate Callback/Listeners Implementation**
- **Change HTTP Interceptor**. To call Service Method Handler with the Service Class name, the method name and the parameters (Objects)
- Remove/Move To AppRegistry AppContext and AppContextWebview
- Auto generate all the Adaptive API Implementations and create every Delegate for the Implementations (proxy model)
- Migrate Javadoc to other implementations

**Comment by carloslozano** [comment]
100% implemented. Pending test.
